#!/usr/bin/env sh

# check we're at the top of the cvs tree
# this check is not very good but it will do for now
if [ ! -d 'src' ] ; then
  echo "not at top of CVS reposity";
  exit;
fi

# make a live directory
mkdir -p dev

# make the top level files
./scripts/src2dev.pl <src/header.page >dev/header.page
./scripts/src2dev.pl <src/footer.page >dev/footer.page
./scripts/src2longdev.pl <src/global.page >dev/global.page

# create the image directory
mkdir -p dev/images
cp ./src/images/*.gif ./dev/images
mkdir -p dev/images/bbcpage/v3-0
cp ./src/images/bbcpage/v3-0/*.gif ./dev/images/bbcpage/v3-0
cp ./src/images/bbcpage/v3-0/.htaccess ./dev/images/bbcpage/v3-0
mkdir -p dev/images/bbcpage/v3-3
cp ./src/images/bbcpage/v3-3/.htaccess ./dev/images/bbcpage/v3-3
cp ./src/images/bbcpage/v3-3/*.gif ./dev/images/bbcpage/v3-3
cp ./src/images/bbcpage/v3-3/*.jpg ./dev/images/bbcpage/v3-3

# create the includes directory
mkdir -p dev/includes
./scripts/src2dev.pl <src/includes/footer.page >dev/includes/footer.page
./scripts/src2dev.pl <src/includes/toolbar.page >dev/includes/toolbar.page
cp src/includes/default.* dev/includes/
cp src/includes/*date* dev/includes/
cp src/includes/tbenh.css dev/includes/
cp src/includes/linktrack.js dev/includes/
cp src/includes/survey_bar.sssi dev/includes/
cp src/includes/survey_css.sssi dev/includes/
cp src/includes/survey_values.sssi dev/includes/
mkdir -p dev/includes/bbcpage/test
cp ./src/includes/bbcpage/test/*.shtml ./dev/includes/bbcpage/test
mkdir -p dev/includes/bbcpage/test/includes
cp ./src/includes/bbcpage/test/includes/* ./dev/includes/bbcpage/test/includes
mkdir -p dev/includes/bbcpage/v3-0
cp ./src/includes/bbcpage/v3-0/*.css ./dev/includes/bbcpage/v3-0
cp ./src/includes/bbcpage/v3-0/.htaccess ./dev/includes/bbcpage/v3-0
mkdir -p dev/includes/bbcpage/v3-1
cp ./src/includes/bbcpage/v3-1/*.css ./dev/includes/bbcpage/v3-1
cp ./src/includes/bbcpage/v3-1/.htaccess ./dev/includes/bbcpage/v3-1
mkdir -p dev/includes/bbcpage/v3-2
cp ./src/includes/bbcpage/v3-2/*.css ./dev/includes/bbcpage/v3-2
cp ./src/includes/bbcpage/v3-2/.htaccess ./dev/includes/bbcpage/v3-2
mkdir -p dev/includes/bbcpage/v3-3
cp ./src/includes/bbcpage/v3-3/*.css ./dev/includes/bbcpage/v3-3
cp ./src/includes/bbcpage/v3-3/.htaccess ./dev/includes/bbcpage/v3-3
mkdir -p dev/survey
cp src/survey/survey.sssi dev/survey/
mkdir -p dev/survey/06
cp src/survey/06/.htaccess dev/survey/06/
cp src/survey/06/redir.shtml dev/survey/06/
mkdir -p live/print
cp src/print/.htaccess live/print/

# create the nav directory, where nav5 lives
mkdir -p dev/nav

mkdir -p dev/nav/images
cp src/nav/images/*.gif dev/nav/images
mkdir -p dev/nav/etc
cp src/nav/etc/*.nav dev/nav/etc
cp src/nav/etc/*.htm dev/nav/etc

# creating the nav/hex directories is more complicated
mkdir -p dev/nav/hex
for i in 00 33 66 99 cc ff; do
  for j in 00 33 66 99 cc ff; do
    for k in 00 33 66 99 cc ff; do
      mkdir -p dev/nav/hex/$i$j$k
      cp src/nav/hexsrc/*.nav dev/nav/hex/$i$j$k/
    done
  done
done

echo "Dev creation completed";
